//
//  CurrencyViewModel.swift
//  Tip Calculator
//
//  Created by Sushant Ubale on 9/2/24.
//

import Foundation

struct Currency: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let country: String
}

let currencies: [Currency] = [
    Currency(name: "AED", country: "United Arab Emirates"),
    Currency(name: "AFN", country: "Afghanistan"),
    Currency(name: "ALL", country: "Albania"),
    Currency(name: "AMD", country: "Armenia"),
    Currency(name: "ANG", country: "Netherlands Antilles"),
    Currency(name: "AOA", country: "Angola"),
    Currency(name: "ARS", country: "Argentina"),
    Currency(name: "AUD", country: "Australia"),
    Currency(name: "AWG", country: "Aruba"),
    Currency(name: "AZN", country: "Azerbaijan"),
    Currency(name: "BAM", country: "Bosnia and Herzegovina"),
    Currency(name: "BBD", country: "Barbados"),
    Currency(name: "BDT", country: "Bangladesh"),
    Currency(name: "BGN", country: "Bulgaria"),
    Currency(name: "BHD", country: "Bahrain"),
    Currency(name: "BIF", country: "Burundi"),
    Currency(name: "BMD", country: "Bermuda"),
    Currency(name: "BND", country: "Brunei"),
    Currency(name: "BOB", country: "Bolivia"),
    Currency(name: "BRL", country: "Brazil"),
    Currency(name: "BSD", country: "Bahamas"),
    Currency(name: "BTN", country: "Bhutan"),
    Currency(name: "BWP", country: "Botswana"),
    Currency(name: "BYN", country: "Belarus"),
    Currency(name: "BZD", country: "Belize"),
    Currency(name: "CAD", country: "Canada"),
    Currency(name: "CDF", country: "Democratic Republic of the Congo"),
    Currency(name: "CHF", country: "Switzerland"),
    Currency(name: "CLP", country: "Chile"),
    Currency(name: "CNY", country: "China"),
    Currency(name: "COP", country: "Colombia"),
    Currency(name: "CRC", country: "Costa Rica"),
    Currency(name: "CUP", country: "Cuba"),
    Currency(name: "CVE", country: "Cape Verde"),
    Currency(name: "CZK", country: "Czech Republic"),
    Currency(name: "DJF", country: "Djibouti"),
    Currency(name: "DKK", country: "Denmark"),
    Currency(name: "DOP", country: "Dominican Republic"),
    Currency(name: "DZD", country: "Algeria"),
    Currency(name: "EGP", country: "Egypt"),
    Currency(name: "ERN", country: "Eritrea"),
    Currency(name: "ETB", country: "Ethiopia"),
    Currency(name: "EUR", country: "European Union"),
    Currency(name: "FJD", country: "Fiji"),
    Currency(name: "FKP", country: "Falkland Islands"),
    Currency(name: "FOK", country: "Faroe Islands"),
    Currency(name: "GBP", country: "United Kingdom"),
    Currency(name: "GEL", country: "Georgia"),
    Currency(name: "GGP", country: "Guernsey"),
    Currency(name: "GHS", country: "Ghana"),
    Currency(name: "GIP", country: "Gibraltar"),
    Currency(name: "GMD", country: "The Gambia"),
    Currency(name: "GNF", country: "Guinea"),
    Currency(name: "GTQ", country: "Guatemala"),
    Currency(name: "GYD", country: "Guyana"),
    Currency(name: "HKD", country: "Hong Kong"),
    Currency(name: "HNL", country: "Honduras"),
    Currency(name: "HRK", country: "Croatia"),
    Currency(name: "HTG", country: "Haiti"),
    Currency(name: "HUF", country: "Hungary"),
    Currency(name: "IDR", country: "Indonesia"),
    Currency(name: "ILS", country: "Israel"),
    Currency(name: "IMP", country: "Isle of Man"),
    Currency(name: "INR", country: "India"),
    Currency(name: "IQD", country: "Iraq"),
    Currency(name: "IRR", country: "Iran"),
    Currency(name: "ISK", country: "Iceland"),
    Currency(name: "JEP", country: "Jersey"),
    Currency(name: "JMD", country: "Jamaica"),
    Currency(name: "JOD", country: "Jordan"),
    Currency(name: "JPY", country: "Japan"),
    Currency(name: "KES", country: "Kenya"),
    Currency(name: "KGS", country: "Kyrgyzstan"),
    Currency(name: "KHR", country: "Cambodia"),
    Currency(name: "KID", country: "Kiribati"),
    Currency(name: "KMF", country: "Comoros"),
    Currency(name: "KRW", country: "South Korea"),
    Currency(name: "KWD", country: "Kuwait"),
    Currency(name: "KYD", country: "Cayman Islands"),
    Currency(name: "KZT", country: "Kazakhstan"),
    Currency(name: "LAK", country: "Laos"),
    Currency(name: "LBP", country: "Lebanon"),
    Currency(name: "LKR", country: "Sri Lanka"),
    Currency(name: "LRD", country: "Liberia"),
    Currency(name: "LSL", country: "Lesotho"),
    Currency(name: "LYD", country: "Libya"),
    Currency(name: "MAD", country: "Morocco"),
    Currency(name: "MDL", country: "Moldova"),
    Currency(name: "MGA", country: "Madagascar"),
    Currency(name: "MKD", country: "North Macedonia"),
    Currency(name: "MMK", country: "Myanmar"),
    Currency(name: "MNT", country: "Mongolia"),
    Currency(name: "MOP", country: "Macau"),
    Currency(name: "MRU", country: "Mauritania"),
    Currency(name: "MUR", country: "Mauritius"),
    Currency(name: "MVR", country: "Maldives"),
    Currency(name: "MWK", country: "Malawi"),
    Currency(name: "MXN", country: "Mexico"),
    Currency(name: "MYR", country: "Malaysia"),
    Currency(name: "MZN", country: "Mozambique"),
    Currency(name: "NAD", country: "Namibia"),
    Currency(name: "NGN", country: "Nigeria"),
    Currency(name: "NIO", country: "Nicaragua"),
    Currency(name: "NOK", country: "Norway"),
    Currency(name: "NPR", country: "Nepal"),
    Currency(name: "NZD", country: "New Zealand"),
    Currency(name: "OMR", country: "Oman"),
    Currency(name: "PAB", country: "Panama"),
    Currency(name: "PEN", country: "Peru"),
    Currency(name: "PGK", country: "Papua New Guinea"),
    Currency(name: "PHP", country: "Philippines"),
    Currency(name: "PKR", country: "Pakistan"),
    Currency(name: "PLN", country: "Poland"),
    Currency(name: "PYG", country: "Paraguay"),
    Currency(name: "QAR", country: "Qatar"),
    Currency(name: "RON", country: "Romania"),
    Currency(name: "RSD", country: "Serbia"),
    Currency(name: "RUB", country: "Russia"),
    Currency(name: "RWF", country: "Rwanda"),
    Currency(name: "SAR", country: "Saudi Arabia"),
    Currency(name: "SBD", country: "Solomon Islands"),
    Currency(name: "SCR", country: "Seychelles"),
    Currency(name: "SDG", country: "Sudan"),
    Currency(name: "SEK", country: "Sweden"),
    Currency(name: "SGD", country: "Singapore"),
    Currency(name: "SHP", country: "Saint Helena"),
    Currency(name: "SLE", country: "Sierra Leone"),
    Currency(name: "SOS", country: "Somalia"),
    Currency(name: "SRD", country: "Suriname"),
    Currency(name: "SSP", country: "South Sudan"),
    Currency(name: "STN", country: "São Tomé and Príncipe"),
    Currency(name: "SYP", country: "Syria"),
    Currency(name: "SZL", country: "Eswatini"),
    Currency(name: "THB", country: "Thailand"),
    Currency(name: "TJS", country: "Tajikistan"),
    Currency(name: "TMT", country: "Turkmenistan"),
    Currency(name: "TND", country: "Tunisia"),
    Currency(name: "TOP", country: "Tonga"),
    Currency(name: "TRY", country: "Turkey"),
    Currency(name: "TTD", country: "Trinidad and Tobago"),
    Currency(name: "TVD", country: "Tuvalu"),
    Currency(name: "TWD", country: "Taiwan"),
    Currency(name: "TZS", country: "Tanzania"),
    Currency(name: "UAH", country: "Ukraine"),
    Currency(name: "UGX", country: "Uganda"),
    Currency(name: "USD", country: "United States"),
    Currency(name: "UYU", country: "Uruguay"),
    Currency(name: "UZS", country: "Uzbekistan"),
    Currency(name: "VES", country: "Venezuela"),
    Currency(name: "VND", country: "Vietnam"),
    Currency(name: "VUV", country: "Vanuatu"),
    Currency(name: "WST", country: "Samoa"),
    Currency(name: "XAF", country: "CEMAC"),
    Currency(name: "XCD", country: "Organisation of Eastern Caribbean States"),
    Currency(name: "XDR", country: "International Monetary Fund"),
    Currency(name: "XOF", country: "CFA"),
    Currency(name: "XPF", country: "Collectivités d'Outre-Mer"),
    Currency(name: "YER", country: "Yemen"),
    Currency(name: "ZAR", country: "South Africa"),
    Currency(name: "ZMW", country: "Zambia"),
    Currency(name: "ZWL", country: "Zimbabwe")
]
